name: tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', 3.11]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # If you have a requirements file, use:
          # pip install -r requirements.txt
          # Otherwise, install what you need here, for example:
          pip install pytest

      - name: Run tests
        run: |
          pytest tests
